---
abstract: 'send message to HipChat'
author:
  - 'Kazuhiro Homma <kazu.homma@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MadEye-Plugin-Notify-HipChat
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::MadEye::Plugin::Notify::HipChat:
    file: lib/App/MadEye/Plugin/Notify/HipChat.pm
    version: 0.02
requires:
  App::MadEye: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/kazuph/App-MadEye-Plugin-Notify-HipChat/issues
  homepage: https://github.com/kazuph/App-MadEye-Plugin-Notify-HipChat
  repository: git://github.com/kazuph/App-MadEye-Plugin-Notify-HipChat.git
version: 0.02
x_contributors:
  - 'Norimitsu Sasao <norimitsu.sasao@gaiax.com>'
  - 'vagrant <vagrant@localhost.localdomain>'
